create schema ds_0;
create schema ds_1;

CREATE TABLE IF NOT EXISTS ds_0.t_order_0 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_1 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_2 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_3 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_4 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_5 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_6 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_7 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_8 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_9 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_10 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_11 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_12 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_13 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_14 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_0.t_order_15 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));

CREATE TABLE IF NOT EXISTS ds_1.t_order_0 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_1 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_2 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_3 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_4 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_5 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_6 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_7 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_8 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_9 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_10 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_11 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_12 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_13 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_14 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));
CREATE TABLE IF NOT EXISTS ds_1.t_order_15 (order_id BIGINT NOT NULL AUTO_INCREMENT,createDate bigint null,address varchar(32) null,totalPrace int null,userid int null,orderState varchar(3)  null,receiveAddressId varchar(32) null comment '收货地址Id', PRIMARY KEY (order_id));

